kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developers
  namespace: ssatsvc
subjects:
- kind: User
  name: ssatsvc@qualcomm.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
