apiVersion: v1
kind: Namespace
metadata:
  name: ssatsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ssatsvc
  name: developer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
  namespace: ssatsvc
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ssatsvc@qualcomm.com
  namespace: ssatsvc
