apiVersion: v1
kind: Namespace
metadata:
  name: ssatsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ssatsvc
  name: deployer
rules:
- apiGroups: ["*"]
  resources: ["deployments","configmaps","pods","secrets","ingresses"]
  verbs: ["create","get","delete","list","update","edit","watch","exec","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ssatsvc
  name: developer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","describe","list","watch","exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: ssatsvc
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ssatsvc@qualcomm.com
  namespace: ssatsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
  namespace: ssatsvc
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ssatsvc@qualcomm.com
  namespace: ssatsvc
