apiVersion: v1
kind: Namespace
metadata:
  name: ssatsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-developer
  namespace: ssatsvc
roleRef:
  kind: ClusterRole
  name: ns-developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ssatsvc@qualcomm.com
  namespace: ssatsvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-reader
  namespace: ssatsvc
roleRef:
  kind: ClusterRole
  name: ns-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ssatsvc@qualcomm.com
  namespace: ssatsvc
