apiVersion: v1
kind: Namespace
metadata:
  name: k8sshared-developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: k8sshared-developer
  name: developer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
  namespace: k8sshared-developer
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: k8sshared-developer@k8saas-shared1.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
