apiVersion: v1
kind: Namespace
metadata:
  name: k8sshared-developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-developer
  namespace: k8sshared-developer
roleRef:
  kind: ClusterRole
  name: ns-developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: k8sshared-developer@k8saas-shared1.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-reader
  namespace: k8sshared-developer
roleRef:
  kind: ClusterRole
  name: ns-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: k8sshared-developer@k8saas-shared1.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
