apiVersion: v1
kind: Namespace
metadata:
  name: mattyoun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer
  namespace: mattyoun
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: mattyoun@qualcomm.com
  namespace: mattyoun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reader
  namespace: mattyoun
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: mattyoun@qualcomm.com
  namespace: mattyoun
